dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: extreme-casing-384823
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      threads: 4
      keyfile: /home/julio/.dbt/extreme-casing-384823-72e999a0470c.json